name: Automatic Sonar Fix Agent

on:
  workflow_dispatch:

jobs:
  run-sonar-fix:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
      MAX_FIXES_PER_PR: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Sonar Fix Agent
        run: python -m sonar_fix_agent.main
