name: Sonar Fix Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar-fix:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Setup Java (for Maven validation)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ Run Sonar Fix Agent
      - name: Run Sonar Fix Agent
        run: |
          python -m sonar_fix_agent.main
