name: Run Sonar Fix Agent

# Trigger on push to main or manual run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Setup Java (for validator if Maven is used)
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 5️⃣ Create .env file from GitHub Secrets
      - name: Create .env
        run: |
          echo "GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> .env
          echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "GITHUB_REPOSITORY=${{ secrets.REPOSITORY }}" >> .env
          echo "SONAR_URL=${{ secrets.SONAR_URL }}" >> .env

      # 6️⃣ Debug environment variables (optional, can remove later)
      - name: Debug env
        run: |
          cat .env
          echo "GITHUB_REPOSITORY: ${{ secrets.REPOSITORY }}"
          echo "SONAR_URL: ${{ secrets.SONAR_URL }}"

      # 7️⃣ Run the Sonar Fix Agent
      - name: Run Sonar Fix Agent
        run: python -m sonar_fix_agent.main
